---
- name: Patching VMs
  hosts: vm
  roles:
    - { role: ospatch }

- name: Patching host system (proxmox)
  hosts: proxmox
  roles:
    - { role: ospatch }

- name: Patching docker containers
  hosts: docker
  roles:
    - { role: docker }