services:
  teamspeak:
    container_name: teamspeak
    image: mbentley/teamspeak
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 30033:30033
      - 10011:10011
      - 41144:41144
    volumes:
      - /opt/docker/data/teamspeak:/data
      