---
- name: Ensure docker and tools are installed
  apt:
    pkg:
      - docker
      - docker-compose
  become: True

- name: Create base directories compose
  file:
    path: /opt/{{ item }}
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items:
    - docker
    - docker/compose
  become: True

- name: Create base directories data
  file:
    path: /opt/{{ item }}
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items:
    - docker/data
  become: True

- name: Run if on docker server with exposed services
  include_tasks:
    file: docker.yml
  when: "'docker' in group_names"

- name: Run if on docker server with internal services
  include_tasks:
    file: dockerint.yml
  when: "'dockerint' in group_names"